//
// Created by esteban.rosano on 27/6/2022.
//

#ifndef PA___LABORATORIO_3_SUSCRIBIRSEAVIDEOJUEGO_H
#define PA___LABORATORIO_3_SUSCRIBIRSEAVIDEOJUEGO_H
void SuscribirseAVideojuego();
#endif //PA___LABORATORIO_3_SUSCRIBIRSEAVIDEOJUEGO_H
